CONSTRAINT PK_liv PRIMARY KEY(IdLivre);
CONSTRAINT FK_liv FOREIGN KEY(IdOeuvre,Id_auteur);

CONSTRAINT PK_fil PRIMARY KEY(IdFilm);
CONSTRAINT FK_fil FOREIGN KEY(IdOeuvre);

CONSTRAINT PK_al PRIMARY KEY(IdAlbums);
CONSTRAINT FK_al FOREIGN KEY(IdOeuvre);

CONSTRAINT FK_LivrFilm FOREIGN KEY(IdLivres,IdFilm);
CONSTRAINT FK_LivrFilm FOREIGN KEY(IdFilm,IdAlbum);

CONSTRAINT FK_PM FOREIGN KEY(IdChant);

CONSTRAINT FK_AlbumPM FOREIGN KEY(idChant,Id_Album);

CONSTRAINT PK_GenrMus PRIMARY KEY(IdGenreM );

CONSTRAINT PK_PMGenreMus PRIMARY KEY(IdGenreM);
CONSTRAINT FK_PMGenreMus FOREIGN KEY(idChant,Id_Album);

--------
CONSTRAINT PK_Muss PRIMARY KEY(IdGenreM);
CONSTRAINT FK_MusAlbu FOREIGN KEY(IdOeuvre,IdAlbum);

CONSTRAINT PK_Real PRIMARY KEY(Id_realisateur);

CONSTRAINT FK_RealFilm FOREIGN KEY(Id_realisateur,IdFilm);

CONSTRAINT PK_Act PRIMARY KEY(Id_acteur);

CONSTRAINT FK_ActFilm FOREIGN KEY(Id_acteur,IdFilm);

CONSTRAINT PK_GenrFil PRIMARY KEY(Id_genre_film);

CONSTRAINT FK_GenrFilFil FOREIGN KEY(Id_genre_film,IdFilm);

CONSTRAINT PK_Aut PRIMARY KEY(Id_auteur);  

CONSTRAINT PK_Ray PRIMARY KEY(Num_rayon);  
CONSTRAINT FK_Ray FOREIGN KEY(Id_etage);

CONSTRAINT PK_Etag PRIMARY KEY(Id_etage);  

CONSTRAINT PK_Etaggr PRIMARY KEY(Id_étagère);  
CONSTRAINT FK_Etaggr FOREIGN KEY(Num_rayon);

CONSTRAINT PK_OeuvCentr PRIMARY KEY(Num_rayon);  
CONSTRAINT PK_OeuvrRec PRIMARY KEY(Num_rayon);  

CONSTRAINT FK_RayFil FOREIGN KEY(Id_Film,Num_rayon);
CONSTRAINT FK_RayAlbum FOREIGN KEY(IdAlbum,Num_rayon);
CONSTRAINT FK_RayLiv FOREIGN KEY(IdLivres,Num_rayon);



---------  MAJ + Alt + DOWN/UP : dupliquer line
-- CONSTRAINT PK_ PRIMARY KEY();  
-- CONSTRAINT FK_ FOREIGN KEY();
-- CONSTRAINT CHK_  CHECK();